version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sFb-postgres
    restart: always
    environment:
      POSTGRES_DB: sFb_db
      POSTGRES_USER: sFb_user
      POSTGRES_PASSWORD: sFb_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sFb-network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sFb-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - sFb-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sFb-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sFb-network

  jenkins:
    build:
      context: ./jenkins-docker
    container_name: sFb-jenkins
    restart: unless-stopped
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - sFb-network

networks:
  sFb-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  jenkins_home:
    driver: local
