CREATE TABLE IF NOT EXISTS travel_entries (
	id SERIAL PRIMARY KEY,
	location TEXT NOT NULL,
	date DATE NOT NULL,
	description TEXT,
	x INT NOT NULL,
	y INT NOT NULL,
	image_url TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
